# T05 - Motor Trend Car Road Tests

//                |   |
:----------------|---|
| **Nombre**     |  Isabela Torres-Septien Uribe |
| **Fecha**      |  18/09/2025
| **Expediente** |   730667 |

## 1.1 Realiza una regresión tomando 'mpg' como salida y eliminando la columna 'model'. Considera todos los demás factores como numéricos/ordinales.

- 
Calcula el R2 e interpreta los signos de los bet
- .
Realiza un train-test-split donde se use el 40% de los datos para entren
- r. Calcula el R2 de entrenamiento y de prb-
- a.
Añade regularización L2 con un hiperparámetro lambda decidido por ti. Cambia este valor y compara con varios distintos los R2 de entrenamiento y de prueba.

In [171]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import r2_score
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import statsmodels.api as sm


In [172]:
#Exportar datos
df = pd.read_excel("Motor Trend Car Road Tests.xlsx")
data = df.drop(columns = ['model'])
data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [173]:
X = data.drop(columns = ['mpg'])
y = data['mpg']

In [174]:
X = data.drop(columns = ['mpg'])
y = data['mpg']

#Calcula el R2 e interpreta los signos de los betas.
lr = LinearRegression()
lr.fit(X, y)

b0 = lr.intercept_
b1 = lr.coef_

b0,b1


(12.303374155996304,
 array([-0.11144048,  0.01333524, -0.02148212,  0.78711097, -3.71530393,
         0.82104075,  0.31776281,  2.52022689,  0.65541302, -0.19941925]))

In [175]:
y_pred = lr.predict(X)
#Evaluación del modelo
RL_1_1 = r2_score(y, y_pred)
RL_1_1


0.8690157644777647

**Realiza un train-test-split donde se use el 40% de los datos para entrenar. Calcula el R2 de entrenamiento y de prueba.**

In [177]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.4, random_state=137)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


ridge = Ridge(alpha=1.0, fit_intercept=True)
ridge.fit(X_scaled, y)

coef1_1 = ridge.coef_ / scaler.scale_
r_intercept1_1 = ridge.intercept_ - np.dot(scaler.mean_, coef1_1)
r_intercept1_1, coef1_1

(16.53766082999232,
 array([-1.62402755e-01,  2.33307764e-03, -1.49348560e-02,  9.24631319e-01,
        -2.46114602e+00,  4.92587517e-01,  3.74651744e-01,  2.30837578e+00,
         6.85715851e-01, -5.75791252e-01]))

Interpreta  


## 1.2 Repite el ejercicio anterior usando 'qsec' como salida.

In [180]:
X1_2 = data.drop(columns = ['qsec'])
y1_2 = data['qsec']

#Calcula el R2 e interpreta los signos de los betas.
lr = LinearRegression()
lr.fit(X1_2, y1_2)

b0_1_2 = lr.intercept_
b1_1_2 = lr.coef_

b0_1_2,b1_1_2

(17.77617692970129,
 array([ 0.06904768, -0.36267823, -0.00750084, -0.00156255, -0.1310636 ,
         1.49633224,  0.97003474, -0.90118641, -0.20128511, -0.27359751]))

In [181]:
y_pred = lr.predict(X1_2)
#Evaluación del modelo
RL_1_2 = r2_score(y1_2, y_pred)
RL_1_2

0.8746925777093999

In [182]:
x_train, x_test, y_train, y_test = train_test_split(X1_2, y1_2, train_size=0.4, random_state=137)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X1_2)


ridge = Ridge(alpha=1.0, fit_intercept=True)
ridge.fit(X_scaled, y1_2)

coef1_2 = ridge.coef_ / scaler.scale_
r_intercept1_2 = ridge.intercept_ - np.dot(scaler.mean_, coef1_2)
r_intercept1_2, coef1_2

(19.285160637836686,
 array([ 0.04642889, -0.370557  , -0.00378503, -0.00505486, -0.15819341,
         1.03384982,  1.13550633, -0.89999179, -0.24549404, -0.15811703]))

Interpreta  


2.1 Realiza una regresión tomando 'mpg' como salida y eliminando la columna 'model'. Crea columnas dummies para los factores 'cyl', 'gear' y 'carb'.

In [185]:
data2 = pd.get_dummies(df, columns=["cyl", "gear", "carb"], drop_first=True)
data2 = df.drop(columns = ['model'])

X2_1 = data2.drop(columns = ['mpg'])
y2_1 = data2['mpg']

#Calcula el R2 e interpreta los signos de los betas.
lr = LinearRegression()
lr.fit(X2_1, y2_1)

b0_2_1 = lr.intercept_
b1_2_1 = lr.coef_

b0_2_1,b1_2_1

(12.303374155996304,
 array([-0.11144048,  0.01333524, -0.02148212,  0.78711097, -3.71530393,
         0.82104075,  0.31776281,  2.52022689,  0.65541302, -0.19941925]))

In [186]:
y_pred2 = lr.predict(X2_1)
#Evaluación del modelo
RL_2_1 = r2_score(y2_1, y_pred2)
RL_2_1

0.8690157644777647

In [187]:
x_train, x_test, y_train, y_test = train_test_split(X2_1, y2_1, train_size=0.4, random_state=137)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X2_1)


ridge = Ridge(alpha=1.0, fit_intercept=True)
ridge.fit(X_scaled, y2_1)

coef2_1 = ridge.coef_ / scaler.scale_
r_intercept2_1 = ridge.intercept_ - np.dot(scaler.mean_, coef2_1)
r_intercept2_1, coef2_1

(16.53766082999232,
 array([-1.62402755e-01,  2.33307764e-03, -1.49348560e-02,  9.24631319e-01,
        -2.46114602e+00,  4.92587517e-01,  3.74651744e-01,  2.30837578e+00,
         6.85715851e-01, -5.75791252e-01]))

Interpreta  


2.2 Repite el ejercicio anterior usando 'qsec' como salida.

In [190]:
X2_2 = data2.drop(columns = ['qsec'])
y2_2 = data2['qsec']

#Calcula el R2 e interpreta los signos de los betas.
lr = LinearRegression()
lr.fit(X2_2, y2_2)

b02_2 = lr.intercept_
b12_2 = lr.coef_

b02_2,b12_2

(17.77617692970129,
 array([ 0.06904768, -0.36267823, -0.00750084, -0.00156255, -0.1310636 ,
         1.49633224,  0.97003474, -0.90118641, -0.20128511, -0.27359751]))

In [191]:
y_pred2 = lr.predict(X2_2)
#Evaluación del modelo
RL_2_2 = r2_score(y2_2, y_pred2)
RL_2_2

0.8746925777093999

In [192]:
x_train, x_test, y_train, y_test = train_test_split(X2_2, y2_2, train_size=0.4, random_state=137)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X2_2)


ridge = Ridge(alpha=1.0, fit_intercept=True)
ridge.fit(X_scaled, y2_2)

coef2_2 = ridge.coef_ / scaler.scale_
r_intercept2_2 = ridge.intercept_ - np.dot(scaler.mean_, coef2_2)
r_intercept2_2, coef2_2

(19.285160637836686,
 array([ 0.04642889, -0.370557  , -0.00378503, -0.00505486, -0.15819341,
         1.03384982,  1.13550633, -0.89999179, -0.24549404, -0.15811703]))

Interpret  


## 3.1 Compara los R2 de los ejercicios 1.1 & 2.1.

In [195]:
print("La regresión lineal de ridge 1.1: ", RL_1_1, "La regresión lineal de ridge: ", RL_2_1)

La regresión lineal de ridge 1.1:  0.8690157644777647 La regresión lineal de ridge:  0.8690157644777647


In [196]:
r_intercept1_1, coef1_1,

(16.53766082999232,
 array([-1.62402755e-01,  2.33307764e-03, -1.49348560e-02,  9.24631319e-01,
        -2.46114602e+00,  4.92587517e-01,  3.74651744e-01,  2.30837578e+00,
         6.85715851e-01, -5.75791252e-01]))

In [197]:
r_intercept2_1, coef2_1,

(16.53766082999232,
 array([-1.62402755e-01,  2.33307764e-03, -1.49348560e-02,  9.24631319e-01,
        -2.46114602e+00,  4.92587517e-01,  3.74651744e-01,  2.30837578e+00,
         6.85715851e-01, -5.75791252e-01]))

EN el siguiente vemos los mismos resultados, esto a mi parecer no está correcto ya que en la segunda variable quitamos valores que son dummies y que en la primera regresíon se marcaban como irrelevantes

## 3.2 Compara los R2 de los ejercicios 1.2 & 2.2.

In [200]:
print("La regresión lineal de ridge 1.1: ", RL_1_2, "La regresión lineal de ridge: ", RL_2_2)

La regresión lineal de ridge 1.1:  0.8746925777093999 La regresión lineal de ridge:  0.8746925777093999


In [201]:
r_intercept1_2, coef1_2,

(19.285160637836686,
 array([ 0.04642889, -0.370557  , -0.00378503, -0.00505486, -0.15819341,
         1.03384982,  1.13550633, -0.89999179, -0.24549404, -0.15811703]))

In [202]:
r_intercept2_2, coef2_2

(19.285160637836686,
 array([ 0.04642889, -0.370557  , -0.00378503, -0.00505486, -0.15819341,
         1.03384982,  1.13550633, -0.89999179, -0.24549404, -0.15811703]))

El mismo fenomeno está encontrado en la segunda regresión en la cual a pesar de usar qsec como nuestra y nos marcan las mismas variables, por lo que la prueba puede no ser precisa.

En CONCLUSIÓN a pesar de tener valores fuera de lo comun la regresión lineal nos ayudó a darnos cuenta de las variables que más adelante definiriamos como dummies, además de tener una gran diferencia entre nuestro R2 con MPG y con QSEC. Sin embargo, creo que aun así es mejor usar una regresión lineal con dummier. además de confirmar de que MPG  tiene mejores resultados ya que, al ser ligeramente menor es más preciso